import Head from "next/head";

type PropsType= {
  info:string
}

export default function About(props:PropsType) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>About page</h1>
        <p>{props.info}</p>
      </main>
    </>
  );
}

// // 此函数:只在 build 构建时执行，线上环境下，每次请求不会再执行
// export async function getStaticProps() {
//   // 可以 await 异步请求
//   console.log('只在 build 构建时执行')
//   return {
//     props:{
//       info:"请求回来的数据 hello world123"
//     }
//   }
// }

// 在组件中写上getServerSideProps函数，就标记这个组
// 件不会像上面的函数生成静态页面，而是动态计算
export async function getServerSideProps() {
  // 可以 await 异步请求
  
  console.log('每次请求都会执行...')
  return {
    props:{
      info:'请求回来的数据 200'
    }
  }
}